### Register customer
POST http://localhost:8082/customers/register
Content-Type: application/json
Accept: application/json

{
  "name": "Henry Cavill",
  "dateOfBirth": "1983-05-05",
  "email": "info@codeartify.com"
}
> {%
    client.global.set("customerId", response.body);
%}

### Get customer
GET http://localhost:8082/customers/{{customerId}}
Accept: application/json
