### Create customer
POST http://localhost:8082/customers
Content-Type: application/json
Accept: application/json

{
  "name": "New Member",
  "dateOfBirth": "1987-08-12",
  "email": "info@codeartify.com"
}
> {%
    client.global.set("customerId", response.body);
%}

### Get customer
GET http://localhost:8082/customers/{{customerId}}
Accept: application/json

### Get all customers
GET http://localhost:8082/customers
Accept: application/json

### Update customer
PUT http://localhost:8082/customers/{{customerId}}
Content-Type: application/json
Accept: application/json

{
  "name": "Oliver Zihler Updated",
  "dateOfBirth": "1986-08-13",
  "email": "oliver.updated@codeartify.com"
}

### Delete customer
DELETE http://localhost:8082/customers/{{customerId}}
Accept: application/json
