### Activate membership
POST http://localhost:8081/memberships/activate
Content-Type: application/json
Accept: application/json

{
  "customerId": "{{customerId}}",
  "planId": "b55d36e9-b1dc-4d40-9d83-904655303057",
  "signedByGuardian": false
}

> {%
    client.global.set("membershipId", response.body);
%}

### Pause membership
POST http://localhost:8081/memberships/{{membershipId}}/pause

### Reactivate membership
POST http://localhost:8081/memberships/{{membershipId}}/reactivate

### Suspend membership
POST http://localhost:8081/memberships/{{membershipId}}/suspend
