### Register customer
POST http://localhost:8082/customers/register
Content-Type: application/json
Accept: application/json

{
  "name": "QRS Zihler",
  "dateOfBirth": "2010-04-19"
}
> {%
    client.global.set("customerId", response.body);
%}

### Get customer
GET http://localhost:8082/customers/{{customerId}}
Accept: application/json
