server:
  port: 8082
app:
  kafka:
    topics:
      managing-customer: managing-customer.integration-events.v1

spring:
  application:
    name: identity
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
  datasource:
    url: jdbc:postgresql://localhost:5433/identity
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    com.codeartify: DEBUG

